<?php

/**
 * @file
 * Primary module hooks for add_currency module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
function add_currency_theme($existing, $type, $theme, $path)
{
    return [
        'currency_display' => [
            'variables' => [
                'curs_usd' => '',
                'curs_eur' => '',
                'curs_pln' => '',
                'curs_gbp' => '',
            ],
            'template' => 'currency-block',
        ],
    ];
}
